# .gitlab-ci.yml

include:
  - local: "ci-templates/mike.gitlab-ci.yml"
  # - local: 'ci-templates/mkdocs.gitlab-ci.yml'

stages:
  - test
  - pages

# Override rules to keep original rules and restrict to 'develop' branch
pages:
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /publication/ && $CI_COMMIT_BRANCH == "develop"'
