repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v4.0.0-alpha.8" # Use the sha or tag you want to point at
    hooks:
      - id: prettier

  # - repo: local
  #   hooks:
  #     - id: eslint
  #       types: [javascript]
  #       # exclude: venv\ # unfortunatly, the exclude option does not work
  #       description: JavaScript code quality and style linter for developers
  #       name: eslint
  #       entry: npx eslint --fix "docs/**/*.js"
  #       language: node

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-json
        description: checks json files for parseable syntax.
        # - id: pretty-format-json
        #   description: sets a standard for formatting json files.
        # NOT COMPATIBLE WITH PRETTIER, PRETTIER DOES BETTER
        # args: [--autofix, --no-sort-keys]
      - id: check-toml
        description: checks toml files for parseable syntax.
      - id: check-yaml
        description: checks yaml files for parseable syntax.
      - id: end-of-file-fixer
        description: ensures that a file is either empty, or ends with one newline.
      - id: requirements-txt-fixer
        description: sorts entries in requirements.txt.
      - id: trailing-whitespace
        description: trims trailing whitespace.

  - repo: https://github.com/Lucas-C/pre-commit-hooks-lxml
    rev: v1.1.0
    hooks:
      - id: forbid-html-img-without-alt-text
        description: List every <img> tag without a alt= or data-ng-attr-alt= attribute
      - id: forbid-non-std-html-attributes
        description: Detect any non-standard attribute that is not prefixed with data-
      - id: detect-missing-css-classes
        description: Detect unused or missing CSS classes definitions, and abort if any of the later ones is found
        args:
          - --css-files-dir
          - \docs\
          - --html-files-dir
          - \docs\
      - id: html-tags-blacklist
        description: interdire les éléments et attributs nuisant à l'accessibilité, selon les recommendations d'Access42
      - id: html-attributes-blacklist
        description: interdire les éléments et attributs nuisant à l'accessibilité, selon les recommendations d'Access42

  # - repo: https://github.com/motet-a/jinjalint
  #   rev: 01e0a4d8
  #   hooks:
  #     - id: jinjalint
  #       types: [file] # restore the default `types` matching
  #       files: \docs\.(html|sls|md)$
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.39.0
    hooks:
      - id: markdownlint
        description: Fixes the style of Markdown/Commonmark files.
    # - id: markdownlint
    # description: Checks the style of Markdown/Commonmark files.

  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.8.4
    hooks:
      - id: nbqa-black
        description: Run 'black' on a Jupyter Notebook
      - id: nbqa-isort
        description: Run 'isort' on a Jupyter Notebook

  # Using this mirror lets us use mypyc-compiled black, which is about 2x faster
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.2.0
    hooks:
      - id: black
        # It is recommended to specify the latest version of Python
        # supported by your project here, or alternatively use
        # pre-commit's default_language_version, see
        # https://pre-commit.com/#top_level-default_language_version
        language_version: python3.12
