site_name: RFID_M0
site_url:  https://rfid_m0.pages.in2p3.fr/rfid_m0.wiki
site_author: Julien Courtecuisse
site_description: >-
                  Provide information to set up and use the rfid_m0.code

# Repository
repo_name: rfid_m0/rfid_m0.code
repo_url: https://gitlab.in2p3.fr/Julien/rfid_m0.code
# Copyright
copyright: Copyright &copy; 2017 - 2023 IPHC's technical platform MIBE

extra:
# language
   alternate:
      - name: Français
        link: /fr/
        lang: fr
      - name: English
        link: /en/
        lang: en
# site analytics
   analytics:
      provider: google
      property: G-XXXXXXXXXX #TODO leave empty if not using google analytics, else fill
      feedback:
         title: Was this page helpful?
         ratings:
         - icon: material/emoticon-happy-outline
           name: This page was helpful
           data: 1
           note: >-
               Thanks for your feedback!
         - icon: material/emoticon-sad-outline
           name: This page could be improved
           data: 0
           note: >-
               Thanks for your feedback! Help us improve this page by
               <a href=" mailto:julien.courtecuisse@iphc.cnrs.fr?subject=%5Brfid_app.wiki%5D%20Feedback&body=Please%20submit%20your%20feedback "
               target="_blank" rel="noopener">sending us your feedback</a>
              #TODO fill if not using google analytics

# versionning
   version:
      provider: mike # TODO
# Configuration
theme:
   name: material
   logo: assets/image/logo_MIBE.png
   favicon: assets/favicon.ico
   collapse_navigation: false
   features:
     - content.code.copy
     - content.code.annotate
     - navigation.tabs
     - navigation.footer

   palette:
      # Palette toggle for light mode
      - media: "(prefers-color-scheme: light)"
        primary: orange
        scheme: default
        toggle:
          icon: material/brightness-7
          name: Switch to dark mode

      # Palette toggle for dark mode
      - media: "(prefers-color-scheme: dark)"
        primary: orange
        scheme: slate
        toggle:
          icon: material/brightness-4
          name: Switch to system preference
   font:
      text: Roboto
      code: Roboto Mono

# Extensions
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
      guess_lang: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list

extra_javascript:
  - javascripts/feedback.js

nav:
    - Home: index.md

    - User section:
      - Configuration du programme: Configuration-du-programme.md
    - Developper section:
      - TODO liste: 0.0.-TODO-liste.md
      - Check liste: 0.1.-Check-list.md
      - Instructions de montage:
        - Antenne: Antenne.md
        - Malette: Malette.md
        - Electronique: Electronique.md
        - Informatique: Informatique.md

      - Liste des composants: Liste-des-composants.md
      - Pinout: Pinouts.md
      - Power Supply:
        - General view: Power-supply.md
        - Li-Ion battery: Power-supply-Li-Ion.md
        - 12V battery: Power-supply-12V.md
