# python.gitlab-ci.yml

isort:
  stage: linting
  image: python:latest
  before_script:
    - pip install isort
  script:
    - isort . --check-only

black:
  stage: linting
  image: python:latest
  before_script:
    - pip install  black
    - pip install black[jupyter]
  script:
    - black --check .

flake8:
  stage: linting
  image: python:latest
  script:
    - pip install flake8
    - pip install flake8-pyproject
    - flake8 .

pylint:
  stage: linting
  image: python:latest
  before_script:
    - pip install pylint
  script:
    - ls
    - find . -type f -name "*.py" | xargs pylint --rcfile=pyproject.toml
